import { Card, SectionTitle } from "../../components/primitives";
import { PageContainer } from "../../components/layout/AppShell";
import { ScaffoldPage } from "../scaffold";

/**
 * Study — plans & sessions.
 *
 * Next milestones:
 *  1. LearningPlanner output → persisted "plan" entities (due date, per-unit cadence).
 *  2. Study-session recorder: log attempts/time, feed evaluations back into the loop.
 *  3. Session review screen showing mastery delta per session (evidence trail).
 */
export default function StudyPage() {
  return (
    <ScaffoldPage
      title="Study"
      subtitle="Learning plans & session log — wire the planner output to runnable sessions."
      scope={[
        "LearningPlanner computes ranked unit queues from gaps + goal importance",
        "RecommendationEngine picks the single next action with explainable reasons",
        "MasteryEngine applies forgetting decay over time",
      ]}
      nextSteps={[
        "Persist generated plans (LearningPlan entity with schedule & due dates)",
        "Record study sessions: duration, attempts, self-eval → submit evidence",
        "Render a plan timeline view per Learning Space",
      ]}
    />
  );
}

/** Placeholder kept until the plan view lands — documents the intended layout. */
export function StudyPlanPreview() {
  return (
    <PageContainer>
      <SectionTitle
        title="Study"
        subtitle="Learning plans & session log"
      />
      <Card>
        <p className="text-sm text-slate-500">
          Plans generated by the LearningPlanner engine will be listed here, grouped by Learning
          Space, with a per-unit cadence and review schedule.
        </p>
      </Card>
    </PageContainer>
  );
}
